### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ColinSullivan1**
In preparation of release, update the core NATS and Protobuf dependencies.

Signed-off-by: Colin Sullivan <colin@synadia.com>

### CODE REVIEW

**Comment by ColinSullivan1** [comment]
It's not necessary; I only did that to keep up to date with the latest version.  I can revert and leave it to the users to upgrade.

Just curious - have you had problems in the past when upgrading Protobuf versions?

**Comment by dungpa** [comment]
> Just curious - have you had problems in the past when upgrading Protobuf versions?

Sometimes it was painful since our dependencies depended on different versions of Protobuf NuGet packages. It meant adding binding redirects everywhere 😀.

In this case, Protobuf 3.8.1 on NuGet introduced new dependencies on `System.Memory`. For us still being on .NET framework (4.7.2, compatible with .NET Standard 2.0), it brings in more dependencies to deploy with very marginal benefits.

**Comment by ColinSullivan1** [comment]
FYI, I've reverted the protobuf version.

**Comment by dungpa** [comment]
@ColinSullivan1 Thank you for listening to your users 🥇.

**Pull request merged**
