### PR TITLE
Do not close not owned NATS connection (#181)

### PR DESCRIPTION
**Pull request by dorny**
Fixes issue #181 

Not owned NATS connection (i.e. externally provided by `StanOptions.NatsConn`) shouldn't be closed by STAN `Connection`. Other two occurrences of closing the connection are behind `if (ncOwned)` condition. This PR makes this behavior consistent.
It also removes the null check via `?` operator as it is redundant at that place.

### CODE REVIEW

**Comment by dorny** [comment]
Does the CI works for external PRs ? I wouldn't say this commit should break all the tests :)

**Comment by ColinSullivan1** [comment]
No, it shouldn't...   ;) Looks like CI requires an updated version of the SDK.

```
C:\windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
"C:\Program Files\dotnet\dotnet.exe" build D:\a\1\s\src\STAN.sln "-dl:CentralLogger,\"D:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.174.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"*ForwardingLogger,\"D:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.174.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"" -c Release --no-incremental --nologo -p:TreatWarningsAsErrors=true -p:Version=2020.08.27-pre1 -p:InformationalVersion=e8de221828df7d3ad0d8776d0632ae2a419e01f5
A compatible installed .NET Core SDK for global.json version [3.0.100] from [D:\a\1\s\global.json] was not found
Install the [3.0.100] .NET Core SDK or update [D:\a\1\s\global.json] with an installed .NET Core SDK:
```

I can take a look later today or tomorrow, unless you'd like to try to include an SDK update as part of this PR.

**Comment by danielwertheim** [comment]
#183 should take care of the required CI pipeline updates. Could either be included in this PR or accepted separately.

**Comment by ColinSullivan1** [comment]
@dorny, which would you prefer?  I can merge #183 or you can incorporate those changes here as Daniel suggested.  Whatever is easiest for you...

**Comment by dorny** [comment]
I would say fixing the bug and fixing the CI are two separate topics. Let's merge #183 first.

**Comment by dorny** [comment]
Would be then possible to release new version (`0.2.2`) with this fix or what's your planned release schedule?

**Comment by ColinSullivan1** [comment]
@dorny , We appreciate that, thank you.  #183 has been merged.  If you could merge from master branch, hopefully CI will go green and we can merge this.

We release 0.2.2 soon, possibly today or early next week.

**Comment by ColinSullivan1** [comment]
@dorny, Thank you for the contribution!

**Pull request merged**
